version: '3'

services:
  computer-use:
    image: ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ${HOME}/.anthropic:/home/computeruse/.anthropic
    ports:
      - "5901:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    tty: true
    stdin_open: true 